import { Helmet } from 'react-helmet-async';
import { Eye, Target, Settings2, Wrench, Cpu, Truck } from 'lucide-react';
import { PageHero, CallToAction } from '../components/Industrial';
export default function About() {
  return <><Helmet><title>About Us | V Packs</title></Helmet><PageHero variant="about" title="About Us" description="Passion for engineering. Commitment to your growth." />
    <section className="shell story-grid"><div><span className="eyebrow">OUR STORY / SINCE 2017</span><h2>GOOD ENGINEERING.<br />LASTING PARTNERSHIPS.</h2><p>Established in 2017 in Madurai, Tamil Nadu, V Packs specializes in packaging machinery, custom automation and expert servicing.</p><p>We bring together practical mechanical engineering and intelligent controls to help businesses build a more reliable packaging process. From filling and sealing to strapping and wrapping, our focus stays on finding the right solution for your production.</p><div className="story-facts"><div><strong>Madurai</strong><span>Our home. Your engineering partner.</span></div><div><strong>Since 2017</strong><span>Hands-on packaging expertise.</span></div></div></div><div className="story-photo"><img src="/products/asm.png" alt="V Packs automatic taping and strapping machinery"/><span>OUR MACHINERY. YOUR NEXT STEP FORWARD.</span></div></section>
    <section className="vision-section shell"><article><Eye/><div><h3>OUR VISION</h3><p>To empower businesses with reliable, innovative packaging and automation solutions that help them work more efficiently and grow with confidence.</p></div></article><article><Target/><div><h3>OUR MISSION</h3><p>To deliver dependable machinery and expert support, combining thoughtful engineering, practical advice and a commitment to our customers.</p></div></article></section>
    <section className="quote-band"><div className="shell"><span>“</span><h2>ENGINEERING A<br />BETTER TOMORROW.</h2></div></section>
    <section className="shell process-section"><span className="eyebrow">FROM FIRST CONVERSATION TO EVERYDAY PRODUCTION</span><h2>A COMPLETE APPROACH.</h2><div className="process-grid">{[[Settings2,'01','Understand & design','We start with your product, process and requirements.'],[Cpu,'02','Build & integrate','Machinery and controls that work together.'],[Wrench,'03','Test & support','Practical guidance, maintenance and repair.'],[Truck,'04','Keep you moving','Ongoing assistance as your business grows.']].map(([Icon,n,title,text])=>{const I=Icon as typeof Eye;return <article key={String(n)}><I/><span>{String(n)}</span><h3>{String(title)}</h3><p>{String(text)}</p></article>})}</div></section><CallToAction/></>;
}
