import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom';
import { ArrowRight, ShieldCheck, Wrench, Settings2, Factory, FlaskConical, Wheat, Pill, Package, Sparkles } from 'lucide-react';
import products from '../data/products.json';
import { CallToAction } from '../components/Industrial';
const featured = ['VP-PGF200', 'VP-LF-100', 'VP-900L', 'VP-101H'].map(id => products.find(p => p.id === id)!);
export default function Home() {
  return <>
    <Helmet><title>V Packs | Packaging Solutions for a Better Tomorrow</title><meta name="description" content="V Packs packaging machinery, custom automation and expert service. Explore our original range of filling, sealing, strapping and packing machines." /></Helmet>
    <section className="industrial-hero">
      <div className="factory-backdrop" />
      <div className="shell hero-layout">
        <div className="hero-copy"><span className="eyebrow">ENGINEERED IN MADURAI. BUILT FOR YOUR BUSINESS.</span><h1>PACKAGING<br />SOLUTIONS FOR<br />A <span>BETTER</span><br />TOMORROW.</h1><p>Reliable machinery. Thoughtful engineering.<br />Complete packaging solutions that keep you moving.</p><div className="hero-actions"><Link className="action action-red" to="/products">Explore our machines <ArrowRight size={18} /></Link><Link className="hero-secondary" to="/services">Discover our expertise <ArrowRight size={17} /></Link></div></div>
        <div className="hero-product"><span className="technical-label">PRECISION / PERFORMANCE / RELIABILITY</span><img src="/images/generated/web-sealer-hero-clean.png" width="1536" height="1024" alt="V Packs branded Semi Automatic Web Sealer - VP 6540/5540L" fetchPriority="high" /><div className="hero-product-caption"><span className="red-line" /><div><strong>Semi Automatic Web Sealer</strong><small>VP 6540/5540L · Integrated shrink tunnel</small></div></div></div>
      </div>
      <div className="shell hero-stats"><div><strong>2017</strong><span>Our journey began</span></div><div><strong>{products.length}</strong><span>Machines in our range</span></div><div><strong>Custom-built</strong><span>For your production needs</span></div><div><strong>End-to-end</strong><span>Engineering & support</span></div></div>
    </section>
    <section className="shell efficiency-section"><div><span className="eyebrow">MORE THAN MACHINERY</span><h2>ENGINEERED<br />FOR EFFICIENCY.</h2><p>From a single machine to a complete packaging process, V Packs helps you pack smarter. We combine reliable equipment with practical expertise and support you can count on.</p><Link to="/about" className="action action-red">Know V Packs <ArrowRight size={17} /></Link></div><div className="efficiency-image"><img src="/products/asm.png" alt="Automatic Taping & Strapping Machine - VP 102PL" loading="lazy" /><span>AUTOMATIC TAPING & STRAPPING / VP 102PL</span></div><div className="benefits"><div><Settings2 /><h3>Built around your process</h3><p>Solutions for your product and production needs.</p></div><div><ShieldCheck /><h3>Dependable by design</h3><p>Practical machinery for everyday performance.</p></div><div><Wrench /><h3>Support that stays with you</h3><p>Expert service, maintenance and repair.</p></div></div></section>
    <section className="product-section"><div className="shell"><div className="section-heading"><div><span className="eyebrow">FIND YOUR NEXT MACHINE</span><h2>OUR PRODUCT RANGE</h2><p>Reliable. Versatile. Built for your business.</p></div><Link className="text-action" to="/products">View all machines <ArrowRight size={18} /></Link></div><div className="home-products">{featured.map(product => <Link to={`/products?q=${encodeURIComponent(product.id)}`} className="home-product" key={product.id}><div className="product-photo"><img src={product.image} alt={product.name} loading="lazy" /></div><span className="product-category">{product.category}</span><h3>{product.name}</h3><p>{product.description}</p><span className="text-action">View details <ArrowRight size={15} /></span></Link>)}</div></div></section>
    <section className="industries"><div className="shell"><span className="eyebrow">ONE PARTNER. MANY POSSIBILITIES.</span><h2>SOLUTIONS ACROSS INDUSTRIES</h2><div className="industry-grid">{[[Factory,'Food & beverages'],[Pill,'Pharmaceuticals'],[FlaskConical,'Chemicals'],[Sparkles,'Personal care'],[Wheat,'Agro products'],[Package,'And more']].map(([Icon,label])=>{const I=Icon as typeof Factory;return <div key={String(label)}><I size={28}/><span>{String(label)}</span></div>})}</div></div></section>
    <section className="shell services-preview"><div><span className="eyebrow">EXPERTISE AT EVERY STEP</span><h2>WE DESIGN. WE BUILD.<br />WE KEEP YOU RUNNING.</h2></div><div><p>Custom machine design, electrical work and hands-on maintenance. Everything your packaging process needs, with one experienced team.</p><Link to="/services" className="text-action">Explore our services <ArrowRight size={17}/></Link></div></section>
    <CallToAction />
  </>;
}
