import { Link, NavLink, useLocation, useNavigate } from 'react-router-dom';
import { Menu, X, ArrowUpRight, Search, Package } from 'lucide-react';
import { useEffect, useState } from 'react';
import products from '../data/products.json';
import { matchesProduct } from '../data/productSearch';
export default function Navbar() {
 const [open,setOpen]=useState(false); const [search,setSearch]=useState(false); const [query,setQuery]=useState(''); const location=useLocation(); const navigate=useNavigate();
 useEffect(()=>{setOpen(false);setSearch(false);},[location]);
 const results = query.trim() ? products.filter(product => matchesProduct(product, query)) : [];
 return <><a className="skip-link" href="#main-content">Skip to content</a><div className="announcement"><span>WE DESIGN. WE BUILD. WE PACK A BETTER TOMORROW.</span><a href="tel:+917871444915">Let’s talk: +91 78714 44915 <ArrowUpRight size={12}/></a></div><header className="site-header"><div className="shell nav-inner"><Link className="brand" to="/" aria-label="V Packs home"><img className="original-logo" src="/logo-transparent.png" alt="V Packs"/></Link><nav className={open?'main-nav is-open':'main-nav'} aria-label="Main navigation">{[['/','Home'],['/about','About'],['/products','Products'],['/services','Services'],['/contact','Contact']].map(([to,label])=><NavLink key={to} to={to} end>{label}</NavLink>)}</nav><div className="nav-actions"><button className="icon-button" aria-label="Search machinery" aria-expanded={search} onClick={()=>setSearch(!search)}>{search?<X size={20}/>:<Search size={20}/>}</button><Link className="action action-red nav-quote" to="/contact">Enquire now <ArrowUpRight size={16}/></Link><button className="icon-button menu-button" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div>{search&&<form className="shell nav-search" onSubmit={e=>{e.preventDefault();navigate(`/products?q=${encodeURIComponent(query.trim())}`);}}><Search size={20}/><input autoFocus aria-label="Search products" placeholder="Search machines, categories, or model numbers…" value={query} onChange={e=>setQuery(e.target.value)}/><button className="action action-red" type="submit">Search <ArrowUpRight size={16}/></button></form>}{search && query.trim() && <div className="shell nav-search-results"><p role="status">{results.length} products found</p><div className="nav-search-result-list">{results.map(product => <Link key={product.id} to={`/products?q=${encodeURIComponent(product.id)}`} className="nav-search-result"><img src={product.image} alt="" /><span><strong>{product.name}</strong><small>{product.category}</small></span><ArrowUpRight size={16}/></Link>)}</div>{results.length === 0 && <p>Try another machine name, category, or model number.</p>}</div>}</header></>;
}
